services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    restart: unless-stopped
    
  redis:
    image: redis/redis-stack-server:7.2.0-v18
    container_name: redis_stack
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    restart: unless-stopped
    
  redis_test:
    image: redis/redis-stack-server:7.2.0-v18
    container_name: redis_stack-test
    ports:
      - "6380:6379"
    volumes:
      - ./docker/data/redis:/data
    restart: unless-stopped

  rabbitmq:
    image: 'rabbitmq:3.12-management'
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}

volumes:
  redis_data:
