services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    restart: unless-stopped
