require 'unit_helper'

RSpec.describe Api::V1::Messages::GetSearchMessagesController, type: :controller do
  let(:chat_id) { SecureRandom.uuid }
  let(:response) { "Text generated by AI" }
  let(:query_bus) { QueryBusMock.new }
  let(:controller) { described_class.new(query_bus: query_bus) }

  before do
    allow(controller).to receive(:params).and_return({ chat_id: chat_id })
    query_bus.add(SearchMessagesQueryResponseMother.create(response: response))
  end

  after do
    query_bus.clear
  end

  describe 'when a #call method is called' do
    it 'renders response with status 200 Ok' do
      expect(controller).to receive(:render).with(
        hash_including(
          status: :ok,
          json: { response: response }
        )
      )

      controller.call
    end
  end
end
